### ISSUE TITLE
Demo service is not available

### ISSUE THREAD

**Issue by hankh95** [srdc/cds-hooks-example-lipid#1]
Tried the demo service at http://app.srdc.com.tr/cds-demo -it is not working.

**Comment by msfyuksel** [comment]
Hi, http://app.srdc.com.tr/cds-demo is the base URL of the CDS-hooks service. As explained in the README, if you try http://app.srdc.com.tr/cds-demo/cds-services you will reach the discovery service. You can call the actual lipid lowering service at http://app.srdc.com.tr/cds-demo/cds-services/nice-cg181 via a POST request, as is shown at the end of the README.
